---
- name: Create Change Request in SNOW
  hosts: localhost
  gather_facts: no
  vars:
    ansible_python_interpreter: /bin/python3

  tasks:
  - name: include variables
    include_vars: change_request_vars.yml

  - name: Create a change Request
    snow_record:
      state: present
      table: change_request
      username: "{{ sn_username }}"
      password: "{{ sn_password }}"
      instance: "{{ sn_instance }}"
      data:
        severity: "{{ sn_severity }}"
        priority: "{{ sn_priority }}"
        short_description: "This is Test Opened by Anisble"
    register: new_incident

  - debug:
      var: new_incident.record 
  
  - name: Pause for 5 seconds to update ServiceNow
    pause:
      seconds: 8
  

  - name: Modify a change Request
    snow_record:
      state: present
      table: change_request
      username: "{{ sn_username }}"
      password: "{{ sn_password }}"
      instance: "{{ sn_instance }}"
      number: " {{ new_incident.record.task_effective_number }}"
      data:
        state: -3
    register: incident
  
  
  
  - debug:
      var: incident.record.task_effective_number
      

