---
- name: Modify Change Request in SNOW
  hosts: localhost
  gather_facts: no
  vars:
    ansible_python_interpreter: /bin/python3

  tasks:
  - name: include variables
    include_vars: change_request_vars.yml

  - name: Modify a change Request
    snow_record:
      state: present
      table: change_request
      username: "{{ sn_username }}"
      password: "{{ sn_password }}"
      instance: "{{ sn_instance }}"
      number: 
      data:
        severity: "{{ sn_severity }}"
        priority: "{{ sn_priority }}"
        short_description: "This is Test Opened by Anisble"
    register: new_incident
  
  - debug:
      var: new_incident.record

